sudo: required
services:
- docker

env:
  global:
    - secure: "HRrJeZmcz0UCq10XiI62AyVCel/K9sIJ8KBQA0VxZcGgh9W8zIx1vm+bT33HKZ+jwOxKmZPDMSDeZUqmmMIugR7W+lPlV4o+MXtGRj/kTU3nrRfGUVUdY7/3cGr8DQb3ly4ErcIjU8ipwie9bwzGRtxm0fRifWMGWqVWZhm25fbwCk3YyCEjxwg/CdO330WZQBlSraZbXmxlbPbyjltXg9JSyXeWNq+o+sidCC0Kytw879AxmJpmXnRhgTGb94s1eSrsCXNXQiTokuWsyC45PlRYMWja/1KS4Po2ilWReIyVtdGXr7Qjb4ewPEtPvUCoawl53Hrxpf84aGN00m1gfNnFgFUFbfRtfbuApXDgo3IVThvfIeNuCx2WK0xbp6PS/70G4XsbRQZx2aD6Vn7yor9+WqCx/BxlOxa/Y7FGCit6I2DGa3MEEAi76N6t/GuLBksot1KHiytMWZ9ERa/eQr+o3X/h6psOZqc5oPr7Bxg1bur/9yDrMsCxKtHikNyAzECyz2G12wupuNdQFXSyDBqILGoMRCWAKf/CJBs9aG0kQEyn7u6Aar5XtC6HHcw88jbO8fHASaze9SE+v3AcrStxv+23xAfCH5GgKklZaC61TDROIeuP890yKXLsGmrRQLyvRFLtHmqjOv6h7Rid7uWPqZ58JusVPoiUyMYHNv0=" #DOCKER_USER
    - secure: "TIKWMn8IedxQ63PX8CLlvisALfPHdAiBV5jPGCoinhWrXEhYQIm3h//gQnE709K2yMnp5wTZz2MoNF+0io0jf8/dC/e1RYgfNzLXN++IB79kwC9+hudPYw+oHI5M8i60ta1ay0z0S2N5bsOng8okT2wUOixehLwbmg8G8q2lFWUg49qsvxSIBr0gINTw8jjt2WAjqF6ri0BzrgyKo1ViUH3fltvjFbksxbbipPy0lkZ0DFbSzDoxqMKFh/yk2b8JwOrTqnXyPwT4jGQZS96DNUEjeHYSTuijv/PV56Bjd0n+WqQA9d5W/hE2+SfhhMI47WACjI/SupO8XIEBWHa2KNnQOmoXrftPWyMylHHpXbjsYlAYeYVGcULHXNmMAAr33SnEVLidVXRHWh9dYkdrvUaKFgu3twrQQ5QU9UuM5WhGmu1q/1HrfvWqipC7hWEafrk9t+WbiJPD/VmDKP+Nbt8/B8uVVr8TAAnTh3agaWe2ydu7Sc/yip46l3o+25OIohM5Hzsvvr9G6uW24161cuXq6W8WR6Wfy/SFEkWuiIvo8cbGMSmKYemyLvVMxIW6t1tRBF+/z3pg8CcC2qtCjr3cI4v8kpeOXHTSCaiyYFxRI6sCMzEctFsDFsWD8GRlaoDoXlQx50BEjSgOA5dEfEoRcXkx9+MHh9d8H3KZrQ0=" #DOCKER_KEY

before_install:
- docker login -u=$DOCKER_EMAIL -p=$DOCKER_KEY quay.io

script:
- "./build.sh"

notifications:
  slack:
    secure: "B6JGCmLWTpIL5kVXS40eJ+PjZPxt2qtJ18Y6JBLIlxWTo+4y2Cezxt8yFN5G3TY4UDRVmdeMqvCQbnDY1FIMCZaqHkvDevxtlYp2iy+ve+I/AXJcMDDu/i8LdBAvAMrCpQgbDI49oI9iIYC7pdX/MPZ3M4YyRkpa3KepU2qNrW5LHuZhY3YcEDwyqr8tJlxB36cJWEN6R3cB9RKjNWDNHT79UhbdTihJEcmmOa8WRxVMjA0gNyJT3bQotil0lENvDWS0WB6AKXhLi3jBz5Tg6E+IVlUvPA33mp9uFKJtNMJRkeF9KceIM/HAv4bulGUxXWGSa/4bsQMC7Z06zVZ4Hk/yzqISVx3BE53KWrfnwpRCpjF4c2j0avcLIq1VaRMAEH3+a3ToK7KtMo5KnkebAcKQFLcFoBOWL6rd9B6eM6SUvPahfYIlLz71QxAMXl/hoiPdpkjs8j2j7kIJx7QrrsYqU7aRmd27dUR9TI2Yoklq7fO5CTWYEogC2+799hEnxINoTEHUzUGUnfPataHDD9IcFOJ/c5+gvxhwYJrTbX7+DACmnKBVLbMfs0SDYDkNxRQvtWFpCUxViYtd8afeqXOaHmNtbnGne8iw+3ZEMIHEpaLgODrXiiFDeYhtN3cwcwLtAINPc9vrhJ3KMf0TMJOupFiThEl2xGglfvd7jME="
    on_success: always
  